#!/bin/bash

FACENET_EMBEDDINGS_PORTS=(8020 8021)
for PORT in "${FACENET_EMBEDDINGS_PORTS[@]}"; do
    python3 -c "import FaceNet_embeddings_server;
FaceNet_embeddings_server.run_server(${PORT})" &
done

VGG19_EMBEDDINGS_PORTS=(8200 8201 8202 8203 8204 8205 8206 8207 8208 8209
8210 8211 8212 8213 8214 8215 8216 8217 8218 8219
8220 8221 8222 8223 8224 8225 8226 8227 8228 8229
8230 8231 8232 8233 8234 8235 8236 8237 8238 8239
8240 8241 8242 8243 8244 8245 8246 8247 8248 8249
8250 8251 8252 8253 8254 8255 8256 8257 8258 8259 )

for PORT in "${VGG19_EMBEDDINGS_PORTS[@]}"; do
    python -c "import VGG19_embeddings_server;
VGG19_embeddings_server.run_server(${PORT})" &
done



FACE_DETECTION_PORTS=(
8040 8041 8042 8043 8044 8045 8046 8047 8048 8049
8050 8051 8052 8053 8054 8055 8056 8057 8058 8059)
FACE_DETECTOR_ID="'MTCNN'"
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python3 -c "import MTCNN_face_detection_server;
MTCNN_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8080 8081)
#8082 8083 8084)
 #8085 8086 8087 8088 8089)
FACE_DETECTOR_ID="'haarcascade_frontalface_alt_tree.xml'"
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python3 -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8090 8091)
FACE_DETECTOR_ID="'haarcascade_frontalface_default.xml'"
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python3 -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8100 8101)
FACE_DETECTOR_ID="'haarcascade_frontalface_alt.xml'"
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python3 -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8110 8111)
FACE_DETECTOR_ID="'haarcascade_frontalface_alt2.xml'"
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python3 -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done
