#!/bin/bash

EMBEDDINGS_PORTS=(8020 8021 8022 8023 8024 8025 8026 8027 8028 8029)

for PORT in "${EMBEDDINGS_PORTS[@]}"; do
    python -c "import FaceNet_embeddings_server;
FaceNet_embeddings_server.run_server(${PORT})" &
done



FACE_DETECTION_PORTS=(8040 8041 8042 8043 8044 8045 8046 8047 8048 8049)
FACE_DETECTOR_ID=5
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python -c "import MTCNN_face_detection_server;
MTCNN_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8050 8051 8052 8053 8054 8055 8056 8057 8058 8059)
FACE_DETECTOR_ID=4
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8090 8091)
FACE_DETECTOR_ID=1
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8100 8101)
FACE_DETECTOR_ID=2
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done

FACE_DETECTION_PORTS=(8110 8111)
FACE_DETECTOR_ID=3
for PORT in "${FACE_DETECTION_PORTS[@]}"; do
    python -c "import haars_face_detection_server;
haars_face_detection_server.run_server(${PORT},${FACE_DETECTOR_ID})" &
done
