#!/bin/bash

source ~/venv-metal/bin/activate

python3 --version

EMBEDDINGS_PORTS=("$@")

for PORT in "${EMBEDDINGS_PORTS[@]}"; do
    python3 -c "import MobileNet_embeddings_server;
MobileNet_embeddings_server.run_server(${PORT})" &
done
